[Interface]
# Bouncing = 20
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = GNbhe3LgIVNr9mjleZFF5jYeBJnkmX+KhN9A1HGf7WM=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# AZ#21
PublicKey = DhNpGwLwzXGSwKXySOUXcmJStXGoGdlrfPZUtmC1jwY=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 45.83.124.1:51820

PersistentKeepalive = 25