[Interface]
# Bouncing = 6
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 6ANg+ULoSbAxIrGPUCHHi9uYf29uA5d0hOZkcoCRX1o=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# AT#95
PublicKey = P1QvY9fC6v7kb2jI4jQMhHpMKHgKrMR1u/XFVezJ4ys=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 154.47.19.213:51820

PersistentKeepalive = 25