[Interface]
# Bouncing = 5
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = sGazc79KM9alUuYBB9brtOUr/e6+EyxjY0aWbiTZblc=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# BA#6
PublicKey = cvRImu6X+AUhQ5Vl/m2zlqrDwHF5gtRSPY0COPuEJVY=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 185.212.111.98:51820

PersistentKeepalive = 25