[Interface]
# Bouncing = 5
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = wJuX7K/8d2Zn96yvQfKi3Iruf+xcJ2Nwe010T6IA4FI=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# BE#34
PublicKey = ehajSjB9QTlhy30zbemS7ypGrQ+5Ej71jJ/+52JRkGI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 91.90.123.50:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:27:31::10]:51820
PersistentKeepalive = 25