[Interface]
# Bouncing = 3
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = QEQAPoV0IiK4sr8SiykyeGMHJNFFDCzAo4Hwf4U7QXk=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# BE#61
PublicKey = jiIKlk1tiyPgxJ4sP/xy4eCuibeeSlOhPmkNxFR/iA8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 45.128.133.226:51820

PersistentKeepalive = 25