[Interface]
# Bouncing = 15
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = iNyrEaI7YycgK2Q3p9sC900P2opzr/2onAJSf8s0YV8=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# FI#85
PublicKey = +DYe5KRSpKDk9k2SYvM4C2iGKaYgZn9daWitYwm02BI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 66.234.150.2:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a0d:5600:142:21::10]:51820
PersistentKeepalive = 25