[Interface]
# Bouncing = 20
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = eBhNMKggkCubx/+rYVEO1eMmm0vGCGtvuHMzCXEJOV8=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# FI#62
PublicKey = z0Otc6w9MlvMxpTRMhs125k/FcTTqN5TG8oaQ58K2CI=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 193.187.151.98:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a0d:5600:142:22::10]:51820
PersistentKeepalive = 25