[Interface]
# Bouncing = 8
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = GG7Lz6+3RHJjhd+UgP6l3sfPEdeLZGRqXjQ0wQ2xZUs=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# GR#45
PublicKey = Aa/1qhvtTi4czuoUMrbb921EWl8tCPUMajJlzJCqfRY=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.22.85.193:51820

PersistentKeepalive = 25