[Interface]
# Bouncing = 2
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = gNVDMKrQ7n4dQb8OKRPjkLafKehQ/+TAigIVJuZenHs=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# GE#32
PublicKey = 7A19/lMrfmpFZARivC7FS8DcGxMn5uUq9LcOqFjzlDo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 138.199.53.236:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a10:9007:0:1::10]:51820
PersistentKeepalive = 25