[Interface]
# Bouncing = 0
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = APHd9oJzep4KdW7rX9YcJZrmGIXerhJcSzWu96niCW0=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# GR#9
PublicKey = BM3CQJ3Vo8L7aOeeyqADlN2tGcn2VPxZ+gnlKk5gLlg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 45.92.33.162:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:8d:5::10]:51820
PersistentKeepalive = 25