[Interface]
# Bouncing = 0
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = QH2kmDKN+dSJkBIuHOnrFoOQL4170mkWa76HG7QOJFo=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# GE#1
PublicKey = gzOHAosXglyJvyz6GUd0yB2VpqtVAdA2qibp0PTh20U=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 89.249.72.130:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a0d:5600:185:1::10]:51820
PersistentKeepalive = 25