[Interface]
# Bouncing = 3
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = iFJf1M3ax1kj+/lVX9XOmuLg25G7Yk7dghhf9VfUblU=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# HR#52
PublicKey = qr1qdqS8oWa3tKGVqjgsSeZh9NM7R+zKhlnNMMlxqwo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.127.144.158:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a02:6ea0:f413:8092::10]:51820
PersistentKeepalive = 25