[Interface]
# Bouncing = 10
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = mL3X2JCm7nPT6523v3nH57X1TSUnexC5OvPY15EM9Fs=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# IE#15
PublicKey = AFp36cKCIznWgRchU9fE2G9kPK6zcdS+7S/u4drPU1g=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.48.2:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:88:91::10]:51820
PersistentKeepalive = 25