[Interface]
# Bouncing = 20
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = CNG95dAOHXqNeuIG3kvXeS4X9YmomBMM3cUIaIwxgHQ=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# IT#85
PublicKey = 4D4PkMrszUx3+Rj4qLZIH1r7s6VAjS28sl34VG5+JyE=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.22.91.161:51820

PersistentKeepalive = 25