[Interface]
# Bouncing = 0
# NetShield = 1
# Moderate NAT = on
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = CI/W8aTc4NJoTbJnpKG0qkgVAhpoRjNw0fLUYCbvUG8=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# LT#10
PublicKey = BqyPHId2xAJj+iblt82NpDvvFu4BjhHqi2bYBKB20QE=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 130.195.243.2:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a0d:5600:100:1::10]:51820
PersistentKeepalive = 25