[Interface]
# Bouncing = 2
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = eHFDjxP0V2eqolTeq2NXLgM+5HGmoce6fn6mUjhaanY=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# LU#3
PublicKey = 5LDaU9dVpG9EKd9fcfWskFqbbPy/HudT8QGt0Eq4JB4=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 5.253.204.194:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2001:ac8:8:3::10]:51820
PersistentKeepalive = 25