[Interface]
# Bouncing = 14
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = EEbtygsjzQbA+lPCbHd+p3wHLpkJFvuJusOrs6D01HA=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# PT#67
PublicKey = fkBdrgo6NaOI9ICRd+i2mDbieKUzEXkj4vX3ItZ+5lM=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.127.131.222:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a02:6ea0:4b08:6269::10]:51820
PersistentKeepalive = 25